local providers = require("codereview.providers")

describe("providers", function()
  describe("detect_platform", function()
    it("returns github for github.com", function()
      assert.equal("github", providers.detect_platform("github.com"))
    end)
    it("returns gitlab for gitlab.com", function()
      assert.equal("gitlab", providers.detect_platform("gitlab.com"))
    end)
    it("returns gitlab for self-hosted", function()
      assert.equal("gitlab", providers.detect_platform("git.company.com"))
    end)
  end)

  describe("get_provider", function()
    it("returns gitlab provider", function()
      local p = providers.get_provider("gitlab")
      assert.equal("gitlab", p.name)
      assert.is_function(p.list_reviews)
    end)
    it("returns github provider", function()
      local p = providers.get_provider("github")
      assert.equal("github", p.name)
      assert.is_function(p.list_reviews)
    end)
    it("errors on unknown", function()
      assert.has_error(function() providers.get_provider("bitbucket") end)
    end)
  end)
end)
