local config = require("codereview.config")

describe("config", function()
  before_each(function()
    config.reset()
  end)

  it("returns defaults when setup called with no args", function()
    config.setup({})
    local c = config.get()
    assert.is_nil(c.gitlab_url)
    assert.is_nil(c.project)
    assert.is_nil(c.token)
    assert.is_nil(c.picker)
    assert.equals(8, c.diff.context)
    assert.is_true(c.ai.enabled)
    assert.equals("claude", c.ai.claude_cmd)
  end)

  it("merges user config over defaults", function()
    config.setup({ diff = { context = 5 }, picker = "fzf" })
    local c = config.get()
    assert.equals(5, c.diff.context)
    assert.equals("fzf", c.picker)
    assert.is_true(c.ai.enabled)
  end)

  it("validates context range", function()
    config.setup({ diff = { context = 25 } })
    local c = config.get()
    assert.equals(20, c.diff.context)
  end)

  it("defaults diff.scroll_threshold to 50", function()
    config.setup({})
    local c = config.get()
    assert.equals(50, c.diff.scroll_threshold)
  end)
end)
