local git = require("codereview.git")

describe("git.parse_remote", function()
  it("parses SSH remote", function()
    local host, project = git.parse_remote("git@gitlab.com:group/project.git")
    assert.equals("gitlab.com", host)
    assert.equals("group/project", project)
  end)

  it("parses HTTPS remote", function()
    local host, project = git.parse_remote("https://gitlab.com/group/project.git")
    assert.equals("gitlab.com", host)
    assert.equals("group/project", project)
  end)

  it("parses HTTPS without .git suffix", function()
    local host, project = git.parse_remote("https://gitlab.com/group/subgroup/project")
    assert.equals("gitlab.com", host)
    assert.equals("group/subgroup/project", project)
  end)

  it("parses SSH with port", function()
    local host, project = git.parse_remote("ssh://git@gitlab.example.com:2222/team/repo.git")
    assert.equals("gitlab.example.com", host)
    assert.equals("team/repo", project)
  end)

  it("returns nil for invalid remote", function()
    local host, project = git.parse_remote("not-a-url")
    assert.is_nil(host)
    assert.is_nil(project)
  end)
end)

describe("git.detect_project", function()
  it("uses config overrides when set", function()
    local config = require("codereview.config")
    config.setup({ gitlab_url = "https://custom.gitlab.com", project = "my/project" })
    local url, proj = git.detect_project()
    assert.equals("https://custom.gitlab.com", url)
    assert.equals("my/project", proj)
    config.reset()
  end)
end)

describe("git.get_current_branch", function()
  it("returns branch name", function()
    local branch = git.get_current_branch()
    assert.is_string(branch)
    assert.is_true(#branch > 0)
  end)
end)

describe("git.branch_exists", function()
  it("returns true for HEAD", function()
    assert.is_true(git.branch_exists("HEAD"))
  end)

  it("returns false for non-existent branch", function()
    assert.is_false(git.branch_exists("this-branch-does-not-exist-xyz"))
  end)
end)

describe("git.get_default_base", function()
  it("returns main or master if exists", function()
    local base = git.get_default_base()
    -- In most repos, one of these exists
    if base then
      assert.is_true(base == "main" or base == "master")
    end
  end)
end)

describe("git.sanitize_branch_name", function()
  it("replaces slashes with dashes", function()
    assert.equals("feat-auth-login", git.sanitize_branch_name("feat/auth/login"))
  end)

  it("handles branch without slashes", function()
    assert.equals("main", git.sanitize_branch_name("main"))
  end)
end)
