local git = require("codereview.git")

describe("git.parse_remote", function()
  it("parses SSH remote", function()
    local host, project = git.parse_remote("git@gitlab.com:group/project.git")
    assert.equals("gitlab.com", host)
    assert.equals("group/project", project)
  end)

  it("parses HTTPS remote", function()
    local host, project = git.parse_remote("https://gitlab.com/group/project.git")
    assert.equals("gitlab.com", host)
    assert.equals("group/project", project)
  end)

  it("parses HTTPS without .git suffix", function()
    local host, project = git.parse_remote("https://gitlab.com/group/subgroup/project")
    assert.equals("gitlab.com", host)
    assert.equals("group/subgroup/project", project)
  end)

  it("parses SSH with port", function()
    local host, project = git.parse_remote("ssh://git@gitlab.example.com:2222/team/repo.git")
    assert.equals("gitlab.example.com", host)
    assert.equals("team/repo", project)
  end)

  it("returns nil for invalid remote", function()
    local host, project = git.parse_remote("not-a-url")
    assert.is_nil(host)
    assert.is_nil(project)
  end)
end)

describe("git.detect_project", function()
  it("uses config overrides when set", function()
    local config = require("codereview.config")
    config.setup({ gitlab_url = "https://custom.gitlab.com", project = "my/project" })
    local url, proj = git.detect_project()
    assert.equals("https://custom.gitlab.com", url)
    assert.equals("my/project", proj)
    config.reset()
  end)
end)
