-- tests/codereview/review/session_spec.lua

-- Stub spinner to avoid nvim_win_set_width dependency in headless tests
package.loaded["codereview.ui.spinner"] = {
  open = function() end,
  close = function() end,
  set_label = function() end,
}

local session = require("codereview.review.session")

describe("review.session", function()
  before_each(function()
    session.reset()
  end)

  describe("get()", function()
    it("starts in idle state", function()
      local s = session.get()
      assert.is_false(s.active)
      assert.is_false(s.ai_pending)
      assert.is_nil(s.ai_job_id)
    end)
  end)

  describe("start()", function()
    it("sets active to true", function()
      session.start()
      local s = session.get()
      assert.is_true(s.active)
      assert.is_false(s.ai_pending)
      assert.is_nil(s.ai_job_id)
    end)
  end)

  describe("stop()", function()
    it("deactivates session and clears all state", function()
      session.start()
      session.ai_start(42)
      session.stop()
      local s = session.get()
      assert.is_false(s.active)
      assert.is_false(s.ai_pending)
      assert.is_nil(s.ai_job_id)
    end)
  end)

  describe("ai_start()", function()
    it("sets ai_pending and stores job_id", function()
      session.start()
      session.ai_start(42)
      local s = session.get()
      assert.is_true(s.active)
      assert.is_true(s.ai_pending)
      assert.equals(42, s.ai_job_id)
    end)
  end)

  describe("ai_finish()", function()
    it("clears ai_pending and job_id, keeps active", function()
      session.start()
      session.ai_start(42)
      session.ai_finish()
      local s = session.get()
      assert.is_true(s.active)
      assert.is_false(s.ai_pending)
      assert.is_nil(s.ai_job_id)
    end)
  end)

  describe("reset()", function()
    it("returns to idle state", function()
      session.start()
      session.ai_start(99)
      session.reset()
      local s = session.get()
      assert.is_false(s.active)
      assert.is_false(s.ai_pending)
      assert.is_nil(s.ai_job_id)
    end)
  end)

  describe("ai_start() with multiple jobs", function()
    it("stores job_ids table and sets total count", function()
      session.start()
      session.ai_start({ 10, 20, 30 }, 3)
      local s = session.get()
      assert.is_true(s.ai_pending)
      assert.same({ 10, 20, 30 }, s.ai_job_ids)
      assert.equals(3, s.ai_total)
      assert.equals(0, s.ai_completed)
    end)

    it("wraps single job_id in a table", function()
      session.start()
      session.ai_start(42)
      local s = session.get()
      assert.is_true(s.ai_pending)
      assert.same({ 42 }, s.ai_job_ids)
      assert.equals(1, s.ai_total)
    end)
  end)

  describe("ai_file_done()", function()
    it("increments completed counter", function()
      session.start()
      session.ai_start({ 10, 20 }, 2)
      session.ai_file_done()
      local s = session.get()
      assert.equals(1, s.ai_completed)
      assert.is_true(s.ai_pending)
    end)

    it("calls ai_finish when all files complete", function()
      session.start()
      session.ai_start({ 10, 20 }, 2)
      session.ai_file_done()
      session.ai_file_done()
      local s = session.get()
      assert.equals(2, s.ai_completed)
      assert.is_false(s.ai_pending)
    end)
  end)
end)
