-- tests/codereview/review/session_spec.lua

local session = require("codereview.review.session")

describe("review.session", function()
  before_each(function()
    session.reset()
  end)

  describe("get()", function()
    it("starts in idle state", function()
      local s = session.get()
      assert.is_false(s.active)
      assert.is_false(s.ai_pending)
      assert.is_nil(s.ai_job_id)
    end)
  end)

  describe("start()", function()
    it("sets active to true", function()
      session.start()
      local s = session.get()
      assert.is_true(s.active)
      assert.is_false(s.ai_pending)
      assert.is_nil(s.ai_job_id)
    end)
  end)

  describe("stop()", function()
    it("sets active to false", function()
      session.start()
      session.stop()
      local s = session.get()
      assert.is_false(s.active)
    end)
  end)

  describe("ai_start()", function()
    it("sets ai_pending and stores job_id", function()
      session.start()
      session.ai_start(42)
      local s = session.get()
      assert.is_true(s.active)
      assert.is_true(s.ai_pending)
      assert.equals(42, s.ai_job_id)
    end)
  end)

  describe("ai_finish()", function()
    it("clears ai_pending and job_id, keeps active", function()
      session.start()
      session.ai_start(42)
      session.ai_finish()
      local s = session.get()
      assert.is_true(s.active)
      assert.is_false(s.ai_pending)
      assert.is_nil(s.ai_job_id)
    end)
  end)

  describe("reset()", function()
    it("returns to idle state", function()
      session.start()
      session.ai_start(99)
      session.reset()
      local s = session.get()
      assert.is_false(s.active)
      assert.is_false(s.ai_pending)
      assert.is_nil(s.ai_job_id)
    end)
  end)
end)
