local highlight = require("glab_review.ui.highlight")

describe("ui.highlight", function()
  it("defines all required highlight groups", function()
    highlight.setup()
    local add = vim.api.nvim_get_hl(0, { name = "GlabReviewDiffAdd" })
    assert.truthy(add.bg)
    local del = vim.api.nvim_get_hl(0, { name = "GlabReviewDiffDelete" })
    assert.truthy(del.bg)
    local add_word = vim.api.nvim_get_hl(0, { name = "GlabReviewDiffAddWord" })
    assert.truthy(add_word.bg)
    local del_word = vim.api.nvim_get_hl(0, { name = "GlabReviewDiffDeleteWord" })
    assert.truthy(del_word.bg)
  end)

  it("GlabReviewFileHeader has bold = true", function()
    highlight.setup()
    local hl = vim.api.nvim_get_hl(0, { name = "GlabReviewFileHeader" })
    assert.is_true(hl.bold)
  end)
end)
