local highlight = require("codereview.ui.highlight")

describe("ui.highlight", function()
  it("defines all required highlight groups", function()
    highlight.setup()
    local add = vim.api.nvim_get_hl(0, { name = "CodeReviewDiffAdd" })
    assert.truthy(add.bg)
    local del = vim.api.nvim_get_hl(0, { name = "CodeReviewDiffDelete" })
    assert.truthy(del.bg)
    local add_word = vim.api.nvim_get_hl(0, { name = "CodeReviewDiffAddWord" })
    assert.truthy(add_word.bg)
    local del_word = vim.api.nvim_get_hl(0, { name = "CodeReviewDiffDeleteWord" })
    assert.truthy(del_word.bg)
  end)

  it("CodeReviewFileHeader has bold = true", function()
    highlight.setup()
    local hl = vim.api.nvim_get_hl(0, { name = "CodeReviewFileHeader" })
    assert.is_true(hl.bold)
  end)

  it("defines CodeReviewSummaryButton highlight", function()
    require("codereview.ui.highlight").setup()
    local hl = vim.api.nvim_get_hl(0, { name = "CodeReviewSummaryButton" })
    assert.truthy(hl.fg or hl.bold)
  end)
end)
