local highlight = require("codereview.ui.highlight")

describe("ui.highlight", function()
  it("defines all required highlight groups", function()
    highlight.setup()
    local add = vim.api.nvim_get_hl(0, { name = "CodeReviewDiffAdd" })
    assert.truthy(add.bg)
    local del = vim.api.nvim_get_hl(0, { name = "CodeReviewDiffDelete" })
    assert.truthy(del.bg)
    local add_word = vim.api.nvim_get_hl(0, { name = "CodeReviewDiffAddWord" })
    assert.truthy(add_word.bg)
    local del_word = vim.api.nvim_get_hl(0, { name = "CodeReviewDiffDeleteWord" })
    assert.truthy(del_word.bg)
  end)

  it("CodeReviewFileHeader has bold = true", function()
    highlight.setup()
    local hl = vim.api.nvim_get_hl(0, { name = "CodeReviewFileHeader" })
    assert.is_true(hl.bold)
  end)

  it("defines CodeReviewSummaryButton highlight", function()
    require("codereview.ui.highlight").setup()
    local hl = vim.api.nvim_get_hl(0, { name = "CodeReviewSummaryButton" })
    assert.truthy(hl.fg or hl.bold)
  end)

  it("defines inline markdown highlight groups", function()
    highlight.setup()
    local bold = vim.api.nvim_get_hl(0, { name = "CodeReviewCommentBold" })
    assert.is_true(bold.bold)
    assert.truthy(bold.bg)
    local italic = vim.api.nvim_get_hl(0, { name = "CodeReviewCommentItalic" })
    assert.is_true(italic.italic)
    local code = vim.api.nvim_get_hl(0, { name = "CodeReviewCommentCode" })
    assert.truthy(code.fg)
    assert.truthy(code.bg)
    local strike = vim.api.nvim_get_hl(0, { name = "CodeReviewCommentStrikethrough" })
    assert.is_true(strike.strikethrough)
    local link = vim.api.nvim_get_hl(0, { name = "CodeReviewCommentLink" })
    assert.is_true(link.underline)
    -- Unresolved variants
    local ubold = vim.api.nvim_get_hl(0, { name = "CodeReviewCommentBoldUnresolved" })
    assert.is_true(ubold.bold)
    assert.truthy(ubold.bg)
    local uitalic = vim.api.nvim_get_hl(0, { name = "CodeReviewCommentItalicUnresolved" })
    assert.is_true(uitalic.italic)
    local ucode = vim.api.nvim_get_hl(0, { name = "CodeReviewCommentCodeUnresolved" })
    assert.truthy(ucode.fg)
    local ustrike = vim.api.nvim_get_hl(0, { name = "CodeReviewCommentStrikethroughUnresolved" })
    assert.is_true(ustrike.strikethrough)
    local ulink = vim.api.nvim_get_hl(0, { name = "CodeReviewCommentLinkUnresolved" })
    assert.is_true(ulink.underline)
  end)

  it("defines CodeReviewCommentPending highlight", function()
    highlight.setup()
    local hl = vim.api.nvim_get_hl(0, { name = "CodeReviewCommentPending" })
    assert.is_not_nil(hl.bg)
  end)

  it("defines CodeReviewCommentFailed highlight", function()
    highlight.setup()
    local hl = vim.api.nvim_get_hl(0, { name = "CodeReviewCommentFailed" })
    assert.is_not_nil(hl.bg)
  end)

  it("defines CodeReviewSelectedNote", function()
    highlight.setup()
    local hl = vim.api.nvim_get_hl(0, { name = "CodeReviewSelectedNote" })
    assert.truthy(hl.bg)
  end)

  it("defines AI warning and error highlight groups", function()
    highlight.setup()
    local warning = vim.api.nvim_get_hl(0, { name = "CodeReviewAIWarning" })
    assert.truthy(warning.bg)
    assert.truthy(warning.fg)
    local warning_border = vim.api.nvim_get_hl(0, { name = "CodeReviewAIWarningBorder" })
    assert.truthy(warning_border.fg)
    local error_hl = vim.api.nvim_get_hl(0, { name = "CodeReviewAIError" })
    assert.truthy(error_hl.bg)
    assert.truthy(error_hl.fg)
    local error_border = vim.api.nvim_get_hl(0, { name = "CodeReviewAIErrorBorder" })
    assert.truthy(error_border.fg)
  end)

  it("defines CodeReviewStatusUnresolved and CodeReviewStatusResolved", function()
    highlight.setup()
    local unresolved = vim.api.nvim_get_hl(0, { name = "CodeReviewStatusUnresolved" })
    assert.truthy(unresolved.fg)
    local resolved = vim.api.nvim_get_hl(0, { name = "CodeReviewStatusResolved" })
    assert.truthy(resolved.fg)
  end)

  it("defines CodeReviewAIWarningSign and CodeReviewAIErrorSign with block chars", function()
    highlight.setup()
    local warning_sign = vim.fn.sign_getdefined("CodeReviewAIWarningSign")
    assert.truthy(#warning_sign > 0)
    assert.equals("▌ ", warning_sign[1].text)
    assert.equals("CodeReviewAIWarningBorder", warning_sign[1].texthl)
    local error_sign = vim.fn.sign_getdefined("CodeReviewAIErrorSign")
    assert.truthy(#error_sign > 0)
    assert.equals("█ ", error_sign[1].text)
    assert.equals("CodeReviewAIErrorBorder", error_sign[1].texthl)
  end)

  it("uses full block char for CodeReviewCommentSign and CodeReviewUnresolvedSign", function()
    highlight.setup()
    local comment_sign = vim.fn.sign_getdefined("CodeReviewCommentSign")
    assert.equals("█ ", comment_sign[1].text)
    local unresolved_sign = vim.fn.sign_getdefined("CodeReviewUnresolvedSign")
    assert.equals("█ ", unresolved_sign[1].text)
  end)

  it("defines CodeReviewHunkSeparator highlight", function()
    require("codereview.ui.highlight").setup()
    local hl = vim.api.nvim_get_hl(0, { name = "CodeReviewHunkSeparator" })
    assert.is_not_nil(hl.fg)
  end)
end)

describe("summary redesign highlights", function()
  it("defines header card groups", function()
    require("codereview.ui.highlight").setup()
    local card = vim.api.nvim_get_hl(0, { name = "CodeReviewHeaderCardBorder" })
    assert.is_not_nil(card.fg)
    local state_open = vim.api.nvim_get_hl(0, { name = "CodeReviewStateOpened" })
    assert.is_not_nil(state_open.fg)
  end)

  it("defines activity icon groups", function()
    require("codereview.ui.highlight").setup()
    local commit_icon = vim.api.nvim_get_hl(0, { name = "CodeReviewActivityCommit" })
    assert.is_not_nil(commit_icon.fg)
    local resolve_icon = vim.api.nvim_get_hl(0, { name = "CodeReviewActivityResolved" })
    assert.is_not_nil(resolve_icon.fg)
  end)

  it("defines file path group", function()
    require("codereview.ui.highlight").setup()
    local fp = vim.api.nvim_get_hl(0, { name = "CodeReviewDiscussionFilePath" })
    assert.is_not_nil(fp.fg)
  end)
end)
