local highlight = require("codereview.ui.highlight")

describe("ui.highlight", function()
  it("defines all required highlight groups", function()
    highlight.setup()
    local add = vim.api.nvim_get_hl(0, { name = "CodeReviewDiffAdd" })
    assert.truthy(add.bg)
    local del = vim.api.nvim_get_hl(0, { name = "CodeReviewDiffDelete" })
    assert.truthy(del.bg)
    local add_word = vim.api.nvim_get_hl(0, { name = "CodeReviewDiffAddWord" })
    assert.truthy(add_word.bg)
    local del_word = vim.api.nvim_get_hl(0, { name = "CodeReviewDiffDeleteWord" })
    assert.truthy(del_word.bg)
  end)

  it("CodeReviewFileHeader has bold = true", function()
    highlight.setup()
    local hl = vim.api.nvim_get_hl(0, { name = "CodeReviewFileHeader" })
    assert.is_true(hl.bold)
  end)

  it("defines CodeReviewSummaryButton highlight", function()
    require("codereview.ui.highlight").setup()
    local hl = vim.api.nvim_get_hl(0, { name = "CodeReviewSummaryButton" })
    assert.truthy(hl.fg or hl.bold)
  end)

  it("defines inline markdown highlight groups", function()
    highlight.setup()
    local bold = vim.api.nvim_get_hl(0, { name = "CodeReviewCommentBold" })
    assert.is_true(bold.bold)
    assert.truthy(bold.bg)
    local italic = vim.api.nvim_get_hl(0, { name = "CodeReviewCommentItalic" })
    assert.is_true(italic.italic)
    local code = vim.api.nvim_get_hl(0, { name = "CodeReviewCommentCode" })
    assert.truthy(code.fg)
    assert.truthy(code.bg)
    local strike = vim.api.nvim_get_hl(0, { name = "CodeReviewCommentStrikethrough" })
    assert.is_true(strike.strikethrough)
    local link = vim.api.nvim_get_hl(0, { name = "CodeReviewCommentLink" })
    assert.is_true(link.underline)
    -- Unresolved variants
    local ubold = vim.api.nvim_get_hl(0, { name = "CodeReviewCommentBoldUnresolved" })
    assert.is_true(ubold.bold)
    assert.truthy(ubold.bg)
  end)
end)
