local picker = require("codereview.picker")

describe("picker", function()
  describe("detect", function()
    it("returns nil when no picker is available", function()
      local name = picker.detect()
      assert.is_true(name == nil or type(name) == "string")
    end)
  end)

  describe("get_adapter", function()
    it("errors for unknown picker", function()
      assert.has_error(function()
        picker.get_adapter("nonexistent_picker")
      end)
    end)
  end)

  describe("pick_comments", function()
    it("dispatches to detected adapter", function()
      local ok, err = pcall(function()
        picker.pick_comments({}, function() end, {})
      end)
      assert.is_true(ok or err:find("No picker found") ~= nil)
    end)
  end)

  describe("pick_files", function()
    it("dispatches to detected adapter", function()
      local ok, err = pcall(function()
        picker.pick_files({}, function() end)
      end)
      assert.is_true(ok or err:find("No picker found") ~= nil)
    end)
  end)
end)
