local actions = require("codereview.mr.actions")
describe("mr.actions", function()
  describe("build_merge_params", function()
    it("builds default merge params", function()
      local params = actions.build_merge_params({})
      assert.is_nil(params.squash)
      assert.is_nil(params.should_remove_source_branch)
    end)
    it("includes squash when requested", function()
      local params = actions.build_merge_params({ squash = true })
      assert.is_true(params.squash)
    end)
    it("includes merge_when_pipeline_succeeds", function()
      local params = actions.build_merge_params({ auto_merge = true })
      assert.is_true(params.merge_when_pipeline_succeeds)
    end)
  end)
end)
