local diff = require("glab_review.mr.diff")

describe("mr.diff", function()
  describe("format_line_number", function()
    it("formats dual line numbers", function()
      local text = diff.format_line_number(10, 12)
      assert.truthy(text:find("10"))
      assert.truthy(text:find("12"))
    end)
    it("shows only old line for deletes", function()
      local text = diff.format_line_number(10, nil)
      assert.truthy(text:find("10"))
    end)
    it("shows only new line for adds", function()
      local text = diff.format_line_number(nil, 12)
      assert.truthy(text:find("12"))
    end)
  end)
  describe("format_hidden_line", function()
    it("formats hidden line indicator", function()
      local text = diff.format_hidden_line(18)
      assert.truthy(text:find("18"))
      assert.truthy(text:find("hidden"))
    end)
  end)
  describe("LINE_NR_WIDTH", function()
    it("line number prefix is exactly LINE_NR_WIDTH chars", function()
      local text = diff.format_line_number(10, 12)
      assert.equals(14, #text)
    end)
    it("line number prefix width is consistent for large numbers", function()
      local text = diff.format_line_number(9999, 9999)
      assert.equals(14, #text)
    end)
  end)
end)
