local M = {}

function M.setup()
  vim.api.nvim_set_hl(0, "CodeReviewDiffAdd", { bg = "#2a4a2a", default = true })
  vim.api.nvim_set_hl(0, "CodeReviewDiffDelete", { bg = "#4a2a2a", default = true })
  vim.api.nvim_set_hl(0, "CodeReviewDiffAddWord", { bg = "#3a6a3a", default = true })
  vim.api.nvim_set_hl(0, "CodeReviewDiffDeleteWord", { bg = "#6a3a3a", default = true })
  vim.api.nvim_set_hl(0, "CodeReviewComment", { bg = "#2a2a3a", default = true })
  vim.api.nvim_set_hl(0, "CodeReviewCommentUnresolved", { bg = "#3a2a2a", fg = "#ff9966", default = true })
  -- Inline markdown – resolved
  vim.api.nvim_set_hl(0, "CodeReviewCommentBold", { bg = "#2a2a3a", bold = true, default = true })
  vim.api.nvim_set_hl(0, "CodeReviewCommentItalic", { bg = "#2a2a3a", italic = true, default = true })
  vim.api.nvim_set_hl(0, "CodeReviewCommentCode", { bg = "#1e2030", fg = "#a9b1d6", default = true })
  vim.api.nvim_set_hl(0, "CodeReviewCommentStrikethrough", { bg = "#2a2a3a", strikethrough = true, default = true })
  vim.api.nvim_set_hl(0, "CodeReviewCommentLink", { bg = "#2a2a3a", fg = "#7aa2f7", underline = true, default = true })
  -- Inline markdown – unresolved
  vim.api.nvim_set_hl(0, "CodeReviewCommentBoldUnresolved", { bg = "#3a2a2a", fg = "#ff9966", bold = true, default = true })
  vim.api.nvim_set_hl(0, "CodeReviewCommentItalicUnresolved", { bg = "#3a2a2a", fg = "#ff9966", italic = true, default = true })
  vim.api.nvim_set_hl(0, "CodeReviewCommentCodeUnresolved", { bg = "#1e2030", fg = "#a9b1d6", default = true })
  vim.api.nvim_set_hl(0, "CodeReviewCommentStrikethroughUnresolved", { bg = "#3a2a2a", fg = "#ff9966", strikethrough = true, default = true })
  vim.api.nvim_set_hl(0, "CodeReviewCommentLinkUnresolved", { bg = "#3a2a2a", fg = "#ff9966", underline = true, default = true })
  vim.api.nvim_set_hl(0, "CodeReviewFileChanged", { fg = "#e0af68", default = true })
  vim.api.nvim_set_hl(0, "CodeReviewFileAdded", { fg = "#9ece6a", default = true })
  vim.api.nvim_set_hl(0, "CodeReviewFileDeleted", { fg = "#f7768e", default = true })
  vim.api.nvim_set_hl(0, "CodeReviewHidden", { fg = "#565f89", italic = true, default = true })
  vim.api.nvim_set_hl(0, "CodeReviewCommentBorder", { fg = "#565f89", default = true })
  vim.api.nvim_set_hl(0, "CodeReviewCommentAuthor", { fg = "#7aa2f7", bold = true, default = true })
  vim.api.nvim_set_hl(0, "CodeReviewCommentResolved", { fg = "#9ece6a", default = true })
  vim.api.nvim_set_hl(0, "CodeReviewCommentOutdated", { fg = "#565f89", italic = true, default = true })
  vim.api.nvim_set_hl(0, "CodeReviewAIDraft", { bg = "#2a2a3a", fg = "#bb9af7", default = true })
  vim.api.nvim_set_hl(0, "CodeReviewAIDraftBorder", { fg = "#bb9af7", default = true })
  vim.api.nvim_set_hl(0, "CodeReviewAIWarning", { bg = "#3a3020", fg = "#e0af68", default = true })
  vim.api.nvim_set_hl(0, "CodeReviewAIWarningBorder", { fg = "#e0af68", default = true })
  vim.api.nvim_set_hl(0, "CodeReviewAIError", { bg = "#3a2020", fg = "#f7768e", default = true })
  vim.api.nvim_set_hl(0, "CodeReviewAIErrorBorder", { fg = "#f7768e", default = true })
  vim.api.nvim_set_hl(0, "CodeReviewStatusUnresolved", { fg = "#ff9966", default = true })
  vim.api.nvim_set_hl(0, "CodeReviewStatusResolved", { fg = "#9ece6a", default = true })
  vim.api.nvim_set_hl(0, "CodeReviewCommentContext", { fg = "#565f89", bg = "#1e2030", italic = true, default = true })
  vim.api.nvim_set_hl(0, "CodeReviewCommentPending", { bg = "#2a2a3a", fg = "#565f89", default = true })
  vim.api.nvim_set_hl(0, "CodeReviewCommentFailed", { bg = "#3a2a2a", fg = "#f7768e", default = true })
  vim.api.nvim_set_hl(0, "CodeReviewReplyBorder", { fg = "#7aa2f7", default = true })
  vim.api.nvim_set_hl(0, "CodeReviewEditBorder", { fg = "#e0af68", default = true })
  vim.api.nvim_set_hl(0, "CodeReviewFloatTitle", { fg = "#c8d3f5", bold = true, default = true })
  vim.api.nvim_set_hl(0, "CodeReviewFloatFooterKey", { fg = "#7aa2f7", bold = true, default = true })
  vim.api.nvim_set_hl(0, "CodeReviewFloatFooterText", { fg = "#565f89", default = true })
  vim.api.nvim_set_hl(0, "CodeReviewFileHeader", { bg = "#1e2030", fg = "#c8d3f5", bold = true, default = true })
  vim.api.nvim_set_hl(0, "CodeReviewLineNr", { fg = "#565f89", default = true })
  vim.api.nvim_set_hl(0, "CodeReviewSummaryButton", { fg = "#7aa2f7", bold = true, default = true })
  vim.api.nvim_set_hl(0, "CodeReviewSpinner", { fg = "#7aa2f7", bold = true, default = true })
  vim.api.nvim_set_hl(0, "CodeReviewThreadBorder", { fg = "#7aa2f7", default = true })
  vim.api.nvim_set_hl(0, "CodeReviewThreadMeta", { fg = "#828bb8", default = true })
  vim.api.nvim_set_hl(0, "CodeReviewSelectedNote", { bg = "#2a3a4a", default = true })
  -- Inline markdown – selected note
  vim.api.nvim_set_hl(0, "CodeReviewCommentBoldSelectedNote", { bg = "#2a3a4a", bold = true, default = true })
  vim.api.nvim_set_hl(0, "CodeReviewCommentItalicSelectedNote", { bg = "#2a3a4a", italic = true, default = true })
  vim.api.nvim_set_hl(0, "CodeReviewCommentCodeSelectedNote", { bg = "#1e2030", fg = "#a9b1d6", default = true })
  vim.api.nvim_set_hl(0, "CodeReviewCommentStrikethroughSelectedNote", { bg = "#2a3a4a", strikethrough = true, default = true })
  vim.api.nvim_set_hl(0, "CodeReviewCommentLinkSelectedNote", { bg = "#2a3a4a", fg = "#7aa2f7", underline = true, default = true })
  -- Block-level markdown
  vim.api.nvim_set_hl(0, "CodeReviewMdH1", { fg = "#c8d3f5", bold = true, default = true })
  vim.api.nvim_set_hl(0, "CodeReviewMdH2", { fg = "#c8d3f5", bold = true, default = true })
  vim.api.nvim_set_hl(0, "CodeReviewMdH3", { fg = "#a9b1d6", bold = true, default = true })
  vim.api.nvim_set_hl(0, "CodeReviewMdH4", { fg = "#a9b1d6", bold = true, default = true })
  vim.api.nvim_set_hl(0, "CodeReviewMdH5", { fg = "#828bb8", default = true })
  vim.api.nvim_set_hl(0, "CodeReviewMdH6", { fg = "#828bb8", italic = true, default = true })
  vim.api.nvim_set_hl(0, "CodeReviewMdCodeBlock", { bg = "#1a1b26", default = true })
  vim.api.nvim_set_hl(0, "CodeReviewMdBlockquote", { bg = "#2a2a3a", fg = "#828bb8", italic = true, default = true })
  vim.api.nvim_set_hl(0, "CodeReviewMdBlockquoteBorder", { fg = "#565f89", default = true })
  vim.api.nvim_set_hl(0, "CodeReviewMdTableHeader", { bold = true, bg = "#1e2030", default = true })
  vim.api.nvim_set_hl(0, "CodeReviewMdTableBorder", { fg = "#565f89", default = true })
  vim.api.nvim_set_hl(0, "CodeReviewMdHr", { fg = "#565f89", default = true })
  vim.api.nvim_set_hl(0, "CodeReviewMdListBullet", { fg = "#7aa2f7", default = true })
  vim.api.nvim_set_hl(0, "CodeReviewHunkSeparator", { fg = "#565f89", default = true })
  vim.api.nvim_set_hl(0, "CodeReviewFileUnvisited", { fg = "#565f89", default = true })
  vim.api.nvim_set_hl(0, "CodeReviewFilePartial", { fg = "#e0af68", default = true })
  vim.api.nvim_set_hl(0, "CodeReviewFileReviewed", { fg = "#9ece6a", default = true })
  vim.api.nvim_set_hl(0, "CodeReviewProgressDim", { fg = "#565f89", default = true })
  vim.fn.sign_define("CodeReviewCommentSign", { text = "█ ", texthl = "CodeReviewComment" })
  vim.fn.sign_define("CodeReviewUnresolvedSign", { text = "█ ", texthl = "CodeReviewCommentUnresolved" })
  vim.fn.sign_define("CodeReviewAISign", { text = "▍ ", texthl = "CodeReviewAIDraft" })
  vim.fn.sign_define("CodeReviewAIWarningSign", { text = "▌ ", texthl = "CodeReviewAIWarningBorder" })
  vim.fn.sign_define("CodeReviewAIErrorSign", { text = "█ ", texthl = "CodeReviewAIErrorBorder" })
end

return M
